spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/gerenciador_db
        username: postgres
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
jwt:
    public:
        key: |
            -----BEGIN PUBLIC KEY-----
            
            -----END PUBLIC KEY-----
    private:
        key: |
            -----BEGIN PRIVATE KEY-----
            
            -----END PRIVATE KEY-----
    time:
        expiration: 300